export const ROLES = {
  SUPER_USUARIO: 'SUPER_USUARIO',
  ADMIN: 'ADMIN',
  FUNCIONARIO: 'FUNCIONARIO',
}

export const AUDIT_ACTIONS = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  CONSULTA_API: 'CONSULTA_API',
}
